---
driver:
  name: docker
platforms:
  - name: instance
    image: debian:11
    capabilities:
      - AUDIT_CONTROL
      - SYS_ADMIN
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root